name: Jim Neuner
favicon: null
layout_spectrum: 0.25433
title: Jim Neuner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fdfdfd'
    - '#9e9fa1'
    - '#404d56'
    - '#797977'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
