name: jimneuner
favicon: null
layout_spectrum: 0.25433
typography_spectrum: 0.51038
title: Jim Neuner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79777a'
    - '#353336'
    - '#b5b3b6'
    - '#dad8db'
    - '#b08b3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
